#!/usr/bin/php
<?php
$i=0;
while(is_file("$i.sample")){
    $sample=file("$i.sample",FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES);
    $label=file("$i.label",FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES);
    foreach($sample as $k=>$v)echo $v,"\t",$label[$k],"\n";
    $i++;
}
?>
