#!/usr/bin/php
<?php
/**
* retrieve links from hypercliques(the output of hybrid). the links can be used as constraints in MPCKMeans.
*/
$usage="Usage file";
($file=$argv[1])||exit("$usage\n");
($f=fopen($file,"r"))||exit("Cann't open $file\n");
$constraints=array();
while($v=fgets($f)){
	$v=split(" ",substr($v,0,strpos($v,"(")-1));
	$n=count($v);
	for($i=0;$i<$n;$i++){
		for($j=$i+1;$j<$n;$j++){
			$constraints[$v[$i]]=$v[$j];
		}
	}
}
while(list($k,$v)=each($constraints)){
	if($k<$v)echo $k,"\t",$v;
	else echo $v,"\t",$k;
	echo "\t1\n";
}
?>