#!/usr/bin/env php
<?php
$usage="hcClass file.hc file.cs\n";
if($argc!=3)exit($usage);
$hc=$argv[1];
require("hcRead.php");
$cs=$argv[2];
require("csRead.php");
$CS=array();
$strategy=4;
if($strategy==0)foreach($hc as $line){
	$p=0;
	foreach($line[0] as $item)if($cs[$item][1]>$p)list($p,$i)=array($cs[$item][1],$item);
	foreach($line[0] as $item)list($cs[$item][0],$cs[$item][1])=array($cs[$i][0],$p);
}
if($strategy==1){
foreach($hc as $line){
	$p=0;
	foreach($line[0] as $item)if($cs[$item][1]>$p)list($p,$i)=array($cs[$item][1],$item);
	foreach($line[0] as $item)$CS[$item]=array($cs[$i][0],$cs[$i][1]);
}
foreach($CS as $c=>$s)list($cs[$c][0],$cs[$c][1])=$s;
}
function strategy2($hc,$p=0){
	global $cs;
	$P=array();
	foreach($hc[0] as $item)if($cs[$item][1]>$p){
		if(isset($P[$cs[$item][0]]))$P[$cs[$item][0]]+=$cs[$item][1];
		else $P[$cs[$item][0]]=$cs[$item][1];
	}
	$max=$sum=0;
	foreach($P as $c=>$p){
		$sum+=$p;
		if($p>$max)list($max,$i)=array($p,$c);
	}
	if($sum)return array($i,$max/$sum);
	else return strategy2($hc,$p-0.01);
}
if($strategy==2)foreach($hc as $line){
	$label=strategy2($line);
	foreach($line[0] as $item)list($cs[$item][0],$cs[$item][1])=$label;
}
if($strategy==3){
foreach($hc as $line){
	$label=strategy2($line);
	foreach($line[0] as $item)$CS[$item]=$label;
}
foreach($CS as $c=>$s)list($cs[$c][0],$cs[$c][1])=$s;
}
if($strategy==4)foreach($hc as $line){
	$label=strategy2($line,0.99);
	foreach($line[0] as $item)list($cs[$item][0],$cs[$item][1])=array($label[0],1);
}
if($strategy==5){
foreach($hc as $line){
	$label=strategy2($line,0.99);
	foreach($line[0] as $item)$CS[$item]=$label;
}
foreach($CS as $c=>$s)list($cs[$c][0],$cs[$c][1])=$s;
}
require("csWrite.php");
?>
