#!/usr/bin/env php
<?php
/**
 * filter hc with some conditions
 */
$usage="hcIndex -0 size -1 support -2 confidence file.hc\n";
if($argc==1)exit($usage);
$opt=getopt("0:1:2:");
$size=isset($opt[0])?$opt[0]:0;
$support=isset($opt[1])?$opt[1]:0;
$confidence=isset($opt[2])?$opt[2]:0;
$hc=$argv[$argc-1];
require("hcRead.php");
foreach($hc as $i=>$line){
	if(count($line[0])<$size)unset($hc[$i]);
	if($line[1]<$support)unset($hc[$i]);
	if($line[2]<$confidence)unset($hc[$i]);
}
require("hcWrite.php");
?>
