#!/usr/bin/env php
<?php
/**
 * Read *.sample files and take some classifier result file paths, output samples whose class results are distinct.
 * The classifier result file consists of lines like:
 *  index value probability
 * Notice: instance index in sample file starts from 1, in classifier result file starts from 0.
 */
function distinct($results){
    $n=count($results);
    $sum=0;
    foreach($results as $result){
        $sum+=$result;
    }
    $mean=$sum/$n;
    $distincts=0;
    foreach($results as $result){
        $distincts+=pow($result-$mean,2);
    }
    $distinct=$distincts/$n;
    return $distinct;
}
$predict=array();
$i=0;
while(is_file("$i.sample")){
    $sample=file("$i.sample",FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES);
    foreach($sample as $v){
        $predict[$v-1]=0;
    }
    $i++;
}
$result=array();
$i=1;
while(is_file($argv[$i])){
    $file=file($argv[$i],FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES);
    foreach($file as $line){
        $line=preg_split("/\s+/",$line);
        $result[$line[0]][$i]=$line[1]*$line[2];
    }
    $i++;
}
$count=0;
for($i=0,$ii=count($predict)+count($result);$i<$ii;$i++){
    if(!isset($predict[$i])){
        $predict[$i]=distinct($result[$count]);
        $count++;
    }
}
arsort($predict);
foreach($predict as $k=>$v){
    echo $k+1,"\n";
}
?>
