#!/usr/bin/env php
<?php
/**
 * Read *.sample and *.label files and take some classifier result file paths, output voted result.
 * The classifier result file consists of lines like:
 *  index value probability
 * Notice: instance index in sample file starts from 1, in classifier result file starts from 0.
 */
$predict=array();
$i=0;
while(is_file("$i.sample")){
    $sample=file("$i.sample",FILE_IGNORE_NEW_LINES);
    $label=file("$i.label",FILE_IGNORE_NEW_LINES);
    foreach($sample as $k=>$v){
        $predict[$v-1]=$label[$k];
    }
    $i++;
}
$result=array();
$i=1;
while(is_file($argv[$i])){
    $file=file($argv[$i],FILE_IGNORE_NEW_LINES);
    foreach($file as $line){
        $line=preg_split("/\s+/",$line);
        $result[$line[0]]+=$line[1]*$line[2]/($argc-1);
    }
    $i++;
}
$count=0;
for($i=0,$ii=count($predict)+count($result);$i<$ii;$i++){
    if(isset($predict[$i])){
        echo $predict[$i],"\n";
    }else{
        echo $result[$count],"\n";
        $count++;
    }
}
?>
